# Where things are
source:          .
destination:     ./_site
collections_dir: .
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections:
  posts:
    output:   true


permalink: /:categories/:year/:month/:day/:title.html

# show posts that are released in the future
future: true

owner: Fabian Bull

plugins:
  - jekyll-font-awesome-sass

# Make font-awesome fonts available
font-awesome:
  assets: true
